name: lead_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  timelines: ^0.1.0
  flutter_form_builder: ^9.1.1
  cached_network_image: ^3.3.0
  dropdown_button2: ^2.3.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
